#ifndef __LWP_CONFIG_H__
#define __LWP_CONFIG_H__


#define CONFIGURE_MAXIMUM_POSIX_MESSAGE_QUEUES				64

#define CONFIGURE_MAXIMUM_POSIX_MUTEXES				64

#define CONFIGURE_MAXIMUM_POSIX_THREADS				16

#define CONFIGURE_MAXIMUM_POSIX_SEMAPHORES				64

#define CONFIGURE_MAXIMUM_POSIX_CONDITION_VARIABLES			64

#define CONFIGURE_MAXIMUM_POSIX_QUEUED_SIGNALS				64

#define CONFIGURE_MAXIMUM_POSIX_TIMERS			64

#endif
